"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "fg:teal"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇 "
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:subtext1"
style_root = "fg:red"
format = "[$user ]($style)"

[directory]
style = "fg:teal"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Documentos" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Músicas" = "󰝚 "
"Música" = "󰝚 "
"Pictures" = " "
"Imagens" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:green"
format = "on [$symbol $branch ]($style)"

[git_status]
style = "fg:green"
format = "([\\[$all_status$ahead_behind\\]]($style) )"

[cmd_duration]
min_time = 500
style = "fg:yellow"
format = "took [$duration ]($style)"

[nodejs]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[c]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[rust]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[golang]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[php]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[java]
symbol = " "
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[kotlin]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[haskell]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[python]
symbol = ""
style = "fg:teal"
format = '[[ $symbol( $version) ](fg:teal)]($style)'

[line_break]
disabled = false

[character]
success_symbol = "[❯](bold fg:teal)"
error_symbol = "[❯](bold fg:red)"
vimcmd_symbol = "[❮](bold fg:green)"
vimcmd_replace_one_symbol = "[❮](bold fg:orange)"
vimcmd_replace_symbol = "[❮](bold fg:orange)"
vimcmd_visual_symbol = "[❮](bold fg:lavender)"
