# #######################################################################################
# HYPRLAND CONFIG - MODULAR
# https://wiki.hypr.land/Configuring/
# #######################################################################################

# Resolução, refresh rate e posição de cada monitor
source = ~/.config/hypr/conf.d/monitors.conf

# Variáveis dos programas padrão: terminal, browser, file manager e launcher
source = ~/.config/hypr/conf.d/programs.conf

# Processos iniciados automaticamente com o Hyprland (waybar, swww, clipboard, etc.)
source = ~/.config/hypr/conf.d/autostart.conf

# Variáveis de ambiente: cursor, XDG, toolkits (GTK/Qt), NVIDIA
source = ~/.config/hypr/conf.d/env.conf

# Visual: gaps, bordas, cores, sombra, blur, animações e layout
source = ~/.config/hypr/conf.d/look_and_feel.conf

# Teclado, mouse, touchpad, sensibilidade e gestos
source = ~/.config/hypr/conf.d/input.conf

# Todos os atalhos de teclado e mouse
source = ~/.config/hypr/conf.d/keybinds.conf

# Regras de comportamento por janela (float, foco, posição, supressão de eventos)
source = ~/.config/hypr/conf.d/windowrules.conf
