###################
### MY PROGRAMS ###
###################
# See https://wiki.hypr.land/Configuring/Keywords/

$terminal    = kitty
$browser     = brave
$fileManager = dolphin
$menu        = rofi -show run
