#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = swww-daemon
exec-once = swww img ~/wallpapers/Wallpaper-Bank/wallpapers/Dynamic-Wallpapers/Light/Forest-Light.png
exec-once = kbuildsycoca6
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text  --watch cliphist store  # Stores only text data
exec-once = wl-paste --type image --watch cliphist store  # Stores only image data
exec-once = kwalletd6
exec-once = dunst
exec-once = hypridle
exec-once = nm-applet --indicator
