#############
### INPUT ###
#############
# See https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout  = us,br
    kb_variant =
    kb_model   =
    kb_options =
    kb_rules   =

    follow_mouse = 1
    sensitivity  = 0  # -1.0 - 1.0, 0 = no modification

    touchpad {
        natural_scroll = true
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs
device {
    name        = usb-gaming-mouse-1
    sensitivity = 0   # ajuste de -1.0 a 1.0 conforme quiser
}

device {
    name            = ugtablet-6-inch-pentablet-pen
    output          = HDMI-A-1
#    region_position = 0, 0
#    region_size     = 111, 70
}
